using Microsoft.AspNetCore.Mvc;
using Stock_Management_DataAccess.Entities;
using Stock_Management_Business.DTO;
using Stock_Management_DataAccess;
using System.Threading.Tasks;
using System;
using Stock_Management_Business.Interface;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;

namespace StockManagementAPI.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class SpecificationController : ControllerBase      
    {
        private readonly ISpecificationService _specificationService;
        private readonly ILogger<SpecificationController> _logger;

        public SpecificationController(ISpecificationService specificationService, ILogger<SpecificationController> logger)
        {
            _specificationService = specificationService;
            _logger = logger;   
        }

        [HttpPost]
        public async Task<IActionResult> AddSpecification([FromBody] SpecificationDTO dto)
        {
            try
            {
                _logger.LogInformation("Specification Controller - Add new Specification");
                if (dto == null || string.IsNullOrWhiteSpace(dto.SpecificationName) || string.IsNullOrWhiteSpace(dto.Datatype))
                    return BadRequest("SpecificationName and Datatype are required.");

                // SpecificationId is not expected in input; it will be generated by DB
                var id = await _specificationService.AddSpecificationAsync(dto);
                _logger.LogInformation("Specification added successfully" + id.ToString());
                return Ok(new { SpecificationId = id });
            } 
            catch (Exception ex)
            {
                _logger.LogInformation("An error occurred while creating the specification" + ex.Message);
                return StatusCode(500, new { message = "An error occurred while creating the specification" });
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetAllSpecifications()
        {
            try
            {
                _logger.LogInformation("Specification Controller - Get all Specifications");
                var specs = await _specificationService.GetAllSpecificationsAsync();
                return Ok(specs);
            } catch (Exception ex)
            {
                _logger.LogInformation("An error occurred while getting all the specification" + ex.Message);
                return StatusCode(500, new { message = "An error occurred while getting all the specification" });
            }
        }

        [HttpPost("bulk-import")]
        public async Task<IActionResult> BulkImportSpecifications([FromBody] List<SpecificationDTO> specifications)
        {
            try
            {
                _logger.LogInformation("Bulk Import specification starts");

                if (specifications == null || specifications.Count == 0)
                {
                    _logger.LogInformation("No specifications provided for import.");
                    return BadRequest("No specifications provided for import.");
                }

                var result = await _specificationService.BulkImportSpecifications(specifications);
                if (result.Errors.Count > 0)
                {
                    _logger.LogInformation("Bulk import completed with errors " + result.ToString());
                    return Ok(new { message = "Bulk import completed with errors", result });
                }
                _logger.LogInformation("Bulk import successful");
                return Ok(new { message = "Bulk import successful", result });
            } catch (Exception ex)
            {
                _logger.LogInformation("An error occurred while importing the specification" + ex.Message);
                return StatusCode(500, new { message = "An error occurred while importing the specification" });
            }
        }

        [HttpDelete("DeleteSpecification")]
        public async Task<IActionResult> DeleteSpecification(int specificationid, [FromQuery] int userId = 1)
        {
            try
            {
                _logger.LogInformation("Delete specification starts" + specificationid.ToString());

                var result = await _specificationService.DeleteSpecificationAsync(specificationid, userId);
                if (!result)
                {
                    _logger.LogInformation("Specification not found");
                    return NotFound(new { message = "Specification not found" });
                }
                _logger.LogInformation("Specification deleted successfully");
                return Ok(new { message = "Specification deleted successfully" });
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogInformation(ex.Message.ToString());
                return BadRequest(new { message = ex.Message });
            }
            catch (Exception ex)
            {
                _logger.LogInformation("An error occurred while importing the specification" + ex.Message);
                return StatusCode(500, new { message = "An error occurred while deleting the specification" });
            }
        }

        [HttpPut("UpdateSpecification")]
        public async Task<IActionResult> UpdateSpecification(int specificationid, [FromBody] SpecificationDTO dto)
        {
            try
            {
                _logger.LogInformation("update specification starts" + specificationid.ToString());

                if (dto == null || string.IsNullOrWhiteSpace(dto.SpecificationName) || string.IsNullOrWhiteSpace(dto.Datatype))
                    return BadRequest("SpecificationName and Datatype are required.");

                var result = await _specificationService.UpdateSpecificationAsync(specificationid, dto);
                if (!result)
                {
                    _logger.LogInformation("Specification not found");
                    return NotFound(new { message = "Specification not found" });
                }
                _logger.LogInformation("Specification updated successfully");
                return Ok(new { message = "Specification updated successfully" });
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogInformation(ex.Message.ToString());
                return BadRequest(new { message = ex.Message });
            }
            catch (Exception ex)
            {
                _logger.LogInformation("An error occurred while importing the specification" + ex.Message);
                return StatusCode(500, new { message = "An error occurred while updating the specification" });
            }
        }
    }
}
