using Microsoft.AspNetCore.Mvc;
using Stock_Management_DataAccess.Entities;
using Stock_Management_Business.DTO;
using Stock_Management_DataAccess;
using System.Threading.Tasks;
using System;
using Stock_Management_Business.Interface;
using System.Collections.Generic;

namespace StockManagementAPI.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class SpecificationController : ControllerBase
    {
        private readonly ISpecificationService _specificationService;

        public SpecificationController(ISpecificationService specificationService)
        {
            _specificationService = specificationService;
        }

        [HttpPost]
        public async Task<IActionResult> AddSpecification([FromBody] SpecificationDTO dto)
        {
            if (dto == null || string.IsNullOrWhiteSpace(dto.SpecificationName) || string.IsNullOrWhiteSpace(dto.Datatype))
                return BadRequest("SpecificationName and Datatype are required.");

            // SpecificationId is not expected in input; it will be generated by DB
            var id = await _specificationService.AddSpecificationAsync(dto);
            return Ok(new { SpecificationId = id });
        }

        [HttpGet]
        public async Task<IActionResult> GetAllSpecifications()
        {
            var specs = await _specificationService.GetAllSpecificationsAsync();
            return Ok(specs);
        }

        [HttpPost("bulk-import")]
        public async Task<IActionResult> BulkImportSpecifications([FromBody] List<SpecificationDTO> specifications)
        {
            if (specifications == null || specifications.Count == 0)
                return BadRequest("No specifications provided for import.");

            var result = await _specificationService.BulkImportSpecifications(specifications);
            if (result.Errors.Count > 0)
            {
                return Ok(new { message = "Bulk import completed with errors", result });
            }
            return Ok(new { message = "Bulk import successful", result });
        }
    }
}
