using System.Threading.Tasks;
using Stock_Management_Business.DTO;
using Stock_Management_Business.Interface;
using Stock_Management_DataAccess.Entities;
using Stock_Management_DataAccess;
using AutoMapper;
using Stock_Management_DataAccess.Interfaces;
using System.Collections.Generic;
using System.Linq;

namespace Stock_Management_Business.Service
{
    public class SpecificationService : ISpecificationService
    {
        private readonly ISpecificationRepository _repo;
        private readonly IMapper _mapper;

        public SpecificationService(ISpecificationRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }

        public async Task<int> AddSpecificationAsync(SpecificationDTO dto)
        {
           // var entity = _mapper.Map<SpecificationEntity>(dto);

            var exists = await _repo.SpecificationNameExists(dto.SpecificationName);
            if (exists)
            {
                throw new InvalidOperationException($"Company with code '{dto.SpecificationName}' already exists.");
            }

            var specificationEntity = _mapper.Map<SpecificationEntity>(dto);
            // Set audit fields
            specificationEntity.CreatedBy = dto.UserId;
            specificationEntity.CreatedDate = DateTime.SpecifyKind(DateTime.UtcNow, DateTimeKind.Utc);
            specificationEntity.ModifiedBy = dto.UserId;
            specificationEntity.ModifiedDate = DateTime.SpecifyKind(DateTime.UtcNow, DateTimeKind.Utc);
            specificationEntity.IsActive = dto.IsActive;

            // SpecificationId will be generated by DB
            var result = await _repo.AddSpecificationAsync(specificationEntity);
            return result;
        }

        public async Task<List<SpecificationDTO>> GetAllSpecificationsAsync()
        {
            var entities = await _repo.GetAllSpecificationsAsync();
            return entities.Select(e => _mapper.Map<SpecificationDTO>(e)).ToList();
        }

        public async Task<BulkImportSpecificationResultDTO> BulkImportSpecifications(List<SpecificationDTO> specifications)
        {
            var result = new BulkImportSpecificationResultDTO();
            int importedCount = 0;
            foreach (var dto in specifications)
            {
                try
                {
                    var exists = await _repo.SpecificationNameExists(dto.SpecificationName);
                    if (exists)
                    {
                        result.Errors.Add($"Specification with name '{dto.SpecificationName}' already exists.");
                        continue;
                    }
                    var entity = _mapper.Map<SpecificationEntity>(dto);
                    entity.CreatedBy = dto.UserId;
                    entity.CreatedDate = DateTime.SpecifyKind(DateTime.UtcNow, DateTimeKind.Utc);
                    entity.ModifiedBy = dto.UserId;
                    entity.ModifiedDate = DateTime.SpecifyKind(DateTime.UtcNow, DateTimeKind.Utc);
                    entity.IsActive = dto.IsActive;
                    await _repo.AddSpecificationAsync(entity);
                    importedCount++;
                }
                catch (Exception ex)
                {
                    result.Errors.Add($"Failed to import specification '{dto.SpecificationName}': {ex.Message}");
                }
            }
            result.TotalImported = importedCount;
            return result;
        }
    }
}
